Repository ThisisaNiceTeam/this-is-a-nice-frontend, pull requests merged in 2023-10, with the labels that each got.

#11 홈페이지 헤더 만들기
  .eslintrc.json
  public/svgs/index.ts
  public/svgs/logo.svg
  public/svgs/themeButton.svg
  src/app/Provider.tsx
  src/app/page.tsx
  src/components/Header.tsx
  src/components/HomeButton.tsx
  src/containers/home/Content.tsx
  src/containers/home/index.tsx
  src/styles/global.tsx
Labels: ✨ feat, 🎨 UI

#16 pre-commit 설정
  .eslintignore
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: ⚙️ chore

#15 테스팅 환경 설정 및 샘플 코드 작성
  .eslintignore
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  jest.config.mjs
  jest.setup.ts
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  src/components/HomeButton.spec.tsx
  src/utils/test/createMockRouter.ts
  src/utils/test/index.ts
  src/utils/test/renderWithContext.tsx
  tsconfig.json
Labels: ⚙️ chore, ✅ test

#18 feat: next-themes 적용
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/app/Provider.tsx
  src/app/globals.css
  src/components/Header.tsx
  src/components/ThemedButton.tsx
  src/containers/home/Content.tsx
  src/styles/global.tsx
Labels: ⚙️ chore, 🔨 refactor

#20 테마 버튼 mui로 변경
  next.config.js
  package.json
  pnpm-lock.yaml
  public/svgs/index.ts
  public/svgs/themeButton.svg
  src/app/Provider.tsx
  src/app/page.module.css
  src/components/Header.tsx
  src/components/ThemedButton.spec.tsx
  src/components/ThemedButton.tsx
  tsconfig.json
Labels: ✨ feat, ✅ test

#21 Home 화면 메인 페이지 작업
  src/components/Header.tsx
  src/components/ThemedButton.spec.tsx
  src/components/ThemedButton.tsx
  src/containers/home/Content.tsx
  src/styles/global.tsx
  src/styles/theme.ts
  src/types/emotion.d.ts
Labels: ✨ feat, 🎨 UI

#23 docs: 테스트코드 가이드 문서 작성
  docs/TestButton.spec.tsx
  docs/TestButton.tsx
  docs/test_convention.md
Labels: 📝 docs, ✅ test

#24 홈페이지 반응형으로 구현하기
  src/components/Header.tsx
  src/containers/home/Content.tsx
Labels: 🎨 UI
